describe('Adding new offer', () => {
  beforeEach(() => {
    cy.visit("http://localhost:8080/addOffer")
  })

  it("Adds new offer and redirects user to homepage", () => {
    cy.get('[data-cy="category"] > select').select("Osobné a úžitkové autá").should("have.value", "Osobné a úžitkové autá")
    cy.get('[data-cy="make"] > select').select(1).should("have.value", "Acura")
    cy.get('[data-cy="model"] > input').type("A25").should("have.value", "A25")
    cy.get('[data-cy="fuel"] > select').select(1).should("have.value", "Benzín")
    cy.get('[data-cy="year"] > input').type("2020").should("have.value", "2020")
    cy.get('[data-cy="km"] > input').type("100000").should("have.value", "100000")
    cy.get('[data-cy="price"] > input').type("10000").should("have.value", "10000")
    cy.get('[data-cy="name"] > input').type("Janko Lehotský").should("have.value", "Janko Lehotský")
    cy.get('[data-cy="city"] > input').type("Bratislava").should("have.value", "Bratislava")
    cy.get('[data-cy="street"] > input').type("Hviezdoslavova").should("have.value", "Hviezdoslavova")
    cy.get('[data-cy="house_number"] > input').type("22").should("have.value", "22")
    cy.get('[data-cy="postal_code"] > input').type("811 03").should("have.value", "811 03")
    cy.get('[data-cy="number"] > input').type("+421 156 666").should("have.value", "+421 156 666")
    cy.get('[data-cy="email"] > input').type("jankol@gmail.com").should("have.value", "jankol@gmail.com")
    cy.get('.file-input-button')
      .selectFile(['cypress/fixtures/images/testPicture.jpeg', 'cypress/fixtures/images/testPicture2.jpg']).trigger("change")
    cy.get('[data-cy="submit"]').click()
    cy.url().should("eq", "http://localhost:8080/")
  })

  it("Displays error messages for all validated fields", () => {
    cy.get('[data-cy="category"] > select').select("Osobné a úžitkové autá")
    cy.get('[data-cy="make"] > select').select(1)
    cy.get('[data-cy="model"] > input').type("A25")
    cy.get('[data-cy="fuel"] > select').select(1)
    cy.get('[data-cy="year"] > input').type("202")
    cy.get('[data-cy="km"] > input').type("100000")
    cy.get('[data-cy="price"] > input').type("10000")
    cy.get('[data-cy="name"] > input').type("Janko Lehotský")
    cy.get('[data-cy="city"] > input').type("Bratislava")
    cy.get('[data-cy="street"] > input').type("Hviezdoslavova")
    cy.get('[data-cy="house_number"] > input').type("22")
    cy.get('[data-cy="postal_code"] > input').type("811 0")
    cy.get('[data-cy="number"] > input').type("+421 1")
    cy.get('[data-cy="email"] > input').type("jankolgmail.com")
    cy.get('.file-input-dropzone').attachFile("testTextFile.txt", { subjectType: 'drag-n-drop' })
    cy.get('[data-cy="submit"]').click()

    cy.get('[data-cy="year"] > .error').should("exist")
    cy.get('[data-cy="postal_code"] > .error').should("exist")
    cy.get('[data-cy="number"] > .error').should("exist")
    cy.get('[data-cy="email"] > .error').should("exist")
    cy.get('.file-input-button-container').contains("Nahrávajte iba obrázky")
  })
})